name: face-classifier
channels:
  - defaults
  - pytorch
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - numpy
  - pandas
  - matplotlib
  - scikit-learn
  - scipy
  - pytorch
  - torchvision
  - torchaudio
  - captum
  - opencv-python-headless
  - streamlit
  - jupyter
  - pip:
      - kaggle
      - gitpython
      - selenium
